### ISSUE TITLE
Linux Armv7 Support?

### ISSUE THREAD

**Issue by Wave6677** [mullvad/wgephemeralpeer#2]
Hello, in it's current state, this package doesn't support Armv7, which is what a lot of OpenWrt routers are running. Without an Armv7 build it is impossible for some OpenWrt users to have a quantum secure tunnel.

**Comment by osm** [comment]
Hi,

Thanks for your input!

We have created a new release now (1.0.2) which includes support for Linux ARMv5, Linux ARMv6, Linux ARMv7 and Windows ARM64 now.

**Comment by Wave6677** [comment]
That was fast, thanks for the hard work!! <3
